sudo: false
language: bash

services:
  - docker

stages:
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: deploy
      script:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - ./build.sh --push