version: '3'
services:
  ovehub-ove-asset-manager-service:
    image: datascience/gdo-socket-service:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
