version: '3'
services:
  gdo-socket-service:
    image: datascienceinstitute/gdo-socket-service:${SERVICE_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
